### ISSUE TITLE
recover_indices.npy

### ISSUE THREAD

**Issue by linhan12** [G-JWLee/COINCIDE_code#2]
hi, I want to ask where is "tan_act_37111519_msa_recover_indices.npy" as you referred in line 24 in COINCIDE_code/COINCIDE_cluster/tinyllava/eval/score/merge_values.py? or how can we generate this .npy file?

**Comment by G-JWLee** [comment]
Hi! the "_recover_indices.npy" was inserted to shuffle the target dataset and recover its order during embedding extraction since the difference of language length for each task caused different speed for each GPU. We removed it due to its redundancy, but it seems that it caused the bug. I recovered the original extract_embed.py file. Please check!

**Comment by j-cyoung** [comment]
Hi, I encountered the same issue. It seems the file has not been updated. Will just removing the `recover_indices` work?
```python
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--score_path", type=str, default=".")
    parser.add_argument("--average", action='store_true')
    args = parser.parse_args()

    score_files = sorted(glob.glob(args.score_path + '_[0-9]*.npy'))

    scores = []
    for score_file in score_files:
        scores.append(np.load(score_file))

    scores = np.concatenate(scores)
    if args.average:
        scores = np.mean(scores, axis=0)

    # recover_indices = np.load(args.score_path + '_recover_indices.npy')
    # scores = scores[recover_indices]

    np.save(args.score_path + '.npy', scores)

    for score_file in score_files:
        os.remove(score_file)
    os.remove(args.score_path + '_recover_indices.npy')
```
